name: CI
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true
      - uses: moonrepo/setup-rust@abb2d32350334249b178c401e5ec5836e0cd88d3 # v1
        with:
          components: rustfmt, clippy
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
        with:
          extra_args: --all-files
      - name: Check config schema is up to date
        run: cargo run --bin generate_config_schema && git diff --exit-code schemas/codspeed.schema.json

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          lfs: true
          submodules: true

      - name: "Install rust-toolchain.toml"
        run: rustup toolchain install
      # We use Swatinem/rust-cache to cache cargo registry, index and target in this job
      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2

      # Install memtrack for the memory integration tests
      - name: Install dependencies required for libbpf-sys (vendored feature)
        run: sudo apt-get update && sudo apt-get install -y autopoint bison flex
      - name: Install memtrack
        run: |
          cargo install --path crates/memtrack --locked
      - name: Install exec-harness
        run: |
          cargo install --path crates/exec-harness --locked

      - run: cargo test --all --exclude memtrack --exclude exec-harness

  exec-harness-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true
      - uses: moonrepo/setup-rust@abb2d32350334249b178c401e5ec5836e0cd88d3 # v1
      - name: Run tests
        run: cargo test -p exec-harness

  basic-run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true
      - name: "Install rust-toolchain.toml"
        run: rustup toolchain install
      # We use Swatinem/rust-cache to cache cargo registry, index and target in this job
      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2
      - name: Run tests
        run: cargo run -- exec -m simulation,walltime,memory --skip-upload --warmup-time 0s --max-rounds 5 -- ls -la

  bpf-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          lfs: true
          submodules: true
      - uses: moonrepo/setup-rust@abb2d32350334249b178c401e5ec5836e0cd88d3 # v1
      - name: Install dependencies required for libbpf-sys (vendored feature)
        run: sudo apt-get update && sudo apt-get install -y autopoint bison flex

      - name: Install additional allocators
        run: sudo apt-get install -y libmimalloc-dev libjemalloc-dev

      - name: Run tests
        env:
          RUST_LOG: debug
        run: sudo -E $(which cargo) test -- --test-threads 1 --nocapture
        working-directory: crates/memtrack

      # Since we ran the tests with sudo, the build artifacts will have root ownership
      - name: Clean up
        run: sudo chown -R $USER:$USER . ~/.cargo

  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true

      - name: "Install rust-toolchain.toml"
        run: rustup toolchain install
      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2
      - name: Install cargo codspeed
        uses: taiki-e/install-action@74e87cbfa15a59692b158178d8905a61bf6fca95 # v2
        with:
          tool: cargo-codspeed

      - name: Build benchmarks
        run: cargo codspeed build -p runner-shared
      - name: Run benchmarks
        uses: CodSpeedHQ/action@db35df748deb45fdef0960669f57d627c1956c30 # v4
        with:
          mode: simulation
          run: cargo codspeed run -p runner-shared
